angular.module('house',['house.ctrl','house.service'])
.config(function($stateProvider){
    $stateProvider.state('menu.houseNew',{
        url:'/house-new',
        views:{
            'menu-content':{
                templateUrl:'templates/house/house-new.html',
                controller:'newCtrl'
            }
        }
    })
    .state('menu.housedesc',{
        url:'/house-decoration',
        views:{
            'menu-content':{
                templateUrl:'templates/house/house-decoration.html',
                controller:'descCtrl'
            }
        }
    })   
    .state('menu.picView',{
        url:'/pic-view/:id',
        cache:false,
        views:{
            'menu-content':{
                templateUrl:'templates/house/pic-view.html',
                controller:'picviewCtrl'
                //cache:false
            }
        }
    })
    ;
})
;