angular.module('house',['house.ctrl','house.service'])
.config(function($stateProvider){
    $stateProvider.state('houseNew',{
        url:'/house-new',
        templateUrl:'templates/house/house-new.html',
        controller:'newCtrl'
    })
    .state('housedesc',{
        url:'/house-decoration',
        templateUrl:'templates/house/house-decoration.html',
        controller:'descCtrl'
    })
    .state('houseinfo',{
        url:'/house-info',
        templateUrl:'templates/house/house-info.html',
        controller:'infoCtrl'
    })
    .state('houseUpdate',{
        url:'/house-update',
        cache:false,
        templateUrl:'templates/house/house-new.html',
        controller:'updateCtrl'
    })
    .state('housedescUpdate',{
        url:'/house-desc-update',
        cache:false,
        templateUrl:'templates/house/house-decoration.html',
        controller:'descupdateCtrl'
    })
    ;
})
;