angular.module('notice',['ionic'])
    .controller('c1',function($scope,$http){
    $scope.imgSrc="a.jpg";
    $scope.notices=[];
    $http.get("test.php").success(function(data){
        $scope.notices=data;
    });
    $scope.delete=function(id){
        alert(id);
    };
});